# Generated by Django 2.0.4 on 2018-04-15 14:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipinumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ipinumber',
            name='number',
            field=models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]-\\d{9}-\\d$|^\\d{11}$|^\\d{9}$', message='Must be a valid IPI Number or CAE Number')]),
        ),
        migrations.AlterField(
            model_name='pseudonym',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
