language: python
python:
  - '3.6.5'
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - make create_db
  - python ./manage.py migrate
script:
  - flake8
  - pytest
notifications:
  email: false
  slack:
    secure: ng3zGxnjkm6+PlKUUdkfMNqWkjv4z+qHMkU1/7Vmo/7qYLTavJlttPgVjgeykxdVQjjXqwKAiMVbD8iwP29+ds6O7Ri53Tzcom9uExvSsR8y8PMThOuSVW+kxZANVo5p94OfsG22PD251VfPe1tjr1xReIXt5Ln/VwE6xpB9anaaNxxwRqmDHKFx2WcCOii4aHekHmxu17ce+ZUc4gYXUDrCyTkkwn74pBuYwaXgcucblXA6oRKJgbEiY96rObKpean39chptg94oiUIRJqQk/AhkXv1Ryw5J+AzXeBiTyCH1Gf08dLlqdXcR+GGNDoku0GSl8KDwSNc1MSbt06tBVpuBHsdu7uOkmSgLMZZN4TTBzzMGvjLX9g7u7DI12eNGvI84cEYC/XItV7QxnfzNTIJ0qN3Opd+77rOzIWaO1OEeYhRF2sPnGeDyMbqwvXFlfkbuu1a4GOIkONlnv6/B+r6Zvl/QbGlq2xGL1jI+rAOBFDTTqaXaimDte/H4+J6XYWOz5GhOG/BWM3gm4QQA/o81JkqP1wbUxF4O9HxtAXBsEuNqivG6n/PRoPqlzeE9NCvGiyU3zm1p9oiNzMKQ6BHBodX5+Gwu1kFbkBO8wyxGA+3gTv5BNIA8r9Rm4TKIfB1701QaFvBE7y81r3L5hKGUmqXRrVVifuZ3xiesnE=
    on_failure: always
