# Generated by Django 2.0.4 on 2018-04-28 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cue_position', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_code', models.CharField(blank=True, choices=[('B', 'Background'), ('F', 'Foreground')], max_length=2, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CueSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_title', models.CharField(max_length=255)),
                ('production_company', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('catalogue_number', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=4)),
                ('programme_duration', models.DurationField(blank=True, null=True)),
                ('music_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cue',
            name='cue_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cues.CueSheet'),
        ),
    ]
