# Generated by Django 2.0.4 on 2018-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='origin_code',
            field=models.CharField(blank=True, choices=[('C', 'Commercial (C)'), ('L', 'Library music (L)'), ('P', 'Live performance (P)'), ('V', 'Music video (V)'), ('X', 'Specially commissioned score (X)')], max_length=1),
        ),
    ]
